"""Backward-compatible facade for skill services.

This module re-exports all skill service classes and functions from the
skill subpackage for backward compatibility. New code should import
directly from agent_core.application.services.skill.* modules.

This file does not contain business logic. All implementation has been
moved to the skill subpackage modules.
"""

from agent_core.application.services.skill import (
    ACTIVE_SKILL_REFERENCE_STATUSES,
    ALLOWED_SKILL_PACKAGE_TOOLS,
    CAPABILITY_BRIDGE_VERSION,
    CANDIDATE_MIN_SCORE_DELTA,
    CURATOR_ACTIVATION_REASON_CODES,
    CURATOR_ARCHIVE_REASON_CODES,
    CURATOR_DEACTIVATION_REASON_CODES,
    CURATOR_RESTORE_REASON_CODES,
    CURATOR_SUPPRESSION_REASON_CODES,
    CapabilityBridgeEntry,
    CapabilityRequest,
    CapabilityRequestBridge,
    CapabilitySelection,
    MERGE_OVERLAP_RULE_KEYS,
    MERGE_RELATED_ARTIFACT_STATUSES,
    MERGE_RELATED_ARTIFACT_STATUS_SCAN_ORDER,
    MERGE_SOURCE_ARTIFACT_STATUSES,
    REPLACEMENT_READINESS_MAX_NEGATIVE_USAGE_RATE,
    REPLACEMENT_READINESS_PROMOTE_OBSERVATION_MIN,
    REPLACEMENT_READINESS_SUCCESSFUL_USAGE_MIN,
    RuntimeCapabilityExecutionPlan,
    STABLE_MAX_NEGATIVE_USAGE_RATE,
    STABLE_MIN_SUCCESSFUL_USAGE_COUNT,
    STABLE_NEGATIVE_USAGE_STATUSES,
    STABLE_REQUIRED_PROMOTE_OBSERVATION_COUNT,
    STABLE_SUCCESSFUL_USAGE_STATUSES,
    SkillArtifactLifecycleService,
    SkillCatalogService,
    SkillCandidateService,
    SkillCuratorJobConfig,
    SkillCuratorJobResult,
    SkillCuratorJobService,
    SkillCuratorRecommendationService,
    SkillPatchProposalService,
    SkillReplacementReadiness,
    SkillReplacementReadinessAction,
    SkillReplacementReadinessService,
    SkillReplacementReadinessThresholds,
    SkillReplacementStagingService,
    SkillResolver,
    SkillUsageService,
    RuntimeExplainService,
    RuntimeBindingExplainResult,
    RuntimeBindingReadiness,
    # Phase 2: router and candidate sources
    SkillRouterService,
    SkillCandidateRanker,
    ActiveArtifactCandidateSource,
    BaselineBuiltinCandidateSource,
    StagedArtifactCandidateSource,
    get_bridge_entry,
    list_capabilities,
    matches_rollout_metadata,
    refresh_skill_observability_metrics,
    resolve_capability_to_legacy,
)

__all__ = [
    "ACTIVE_SKILL_REFERENCE_STATUSES",
    "ALLOWED_SKILL_PACKAGE_TOOLS",
    "CAPABILITY_BRIDGE_VERSION",
    "CANDIDATE_MIN_SCORE_DELTA",
    "CURATOR_ACTIVATION_REASON_CODES",
    "CURATOR_ARCHIVE_REASON_CODES",
    "CURATOR_DEACTIVATION_REASON_CODES",
    "CURATOR_RESTORE_REASON_CODES",
    "CURATOR_SUPPRESSION_REASON_CODES",
    "CapabilityBridgeEntry",
    "CapabilityRequest",
    "CapabilityRequestBridge",
    "CapabilitySelection",
    "MERGE_OVERLAP_RULE_KEYS",
    "MERGE_RELATED_ARTIFACT_STATUSES",
    "MERGE_RELATED_ARTIFACT_STATUS_SCAN_ORDER",
    "MERGE_SOURCE_ARTIFACT_STATUSES",
    "REPLACEMENT_READINESS_MAX_NEGATIVE_USAGE_RATE",
    "REPLACEMENT_READINESS_PROMOTE_OBSERVATION_MIN",
    "REPLACEMENT_READINESS_SUCCESSFUL_USAGE_MIN",
    "RuntimeCapabilityExecutionPlan",
    "STABLE_MAX_NEGATIVE_USAGE_RATE",
    "STABLE_MIN_SUCCESSFUL_USAGE_COUNT",
    "STABLE_NEGATIVE_USAGE_STATUSES",
    "STABLE_REQUIRED_PROMOTE_OBSERVATION_COUNT",
    "STABLE_SUCCESSFUL_USAGE_STATUSES",
    "SkillArtifactLifecycleService",
    "SkillCatalogService",
    "SkillCandidateService",
    "SkillCuratorJobConfig",
    "SkillCuratorJobResult",
    "SkillCuratorJobService",
    "SkillCuratorRecommendationService",
    "SkillPatchProposalService",
    "SkillReplacementReadiness",
    "SkillReplacementReadinessAction",
    "SkillReplacementReadinessService",
    "SkillReplacementReadinessThresholds",
    "SkillReplacementStagingService",
    "SkillResolver",
    "SkillUsageService",
    "RuntimeExplainService",
    "RuntimeBindingExplainResult",
    "RuntimeBindingReadiness",
    # Phase 2: router and candidate sources
    "SkillRouterService",
    "SkillCandidateRanker",
    "ActiveArtifactCandidateSource",
    "BaselineBuiltinCandidateSource",
    "StagedArtifactCandidateSource",
    "get_bridge_entry",
    "list_capabilities",
    "matches_rollout_metadata",
    "refresh_skill_observability_metrics",
    "resolve_capability_to_legacy",
]
